"""
Apply the trained v2 physics-informed model to every storm * year scenario
that the manuscript reports, and produce:

    1. A comparison table with one row per scenario containing:
         - storm, display year
         - ground-truth total (only meaningful for the Ike-2008 reference)
         - original NN's published total (from Table 1 of the manuscript)
         - v2 model's total
         - delta vs. original NN (m^3 and %)
    2. A grouped bar plot comparing the three totals side-by-side.

The v2 prediction is generated by:
    - reading each scenario's `final_input_parameters.csv`
    - engineering the same features used to train v2:
        mean_bldg_size_m2 = TBFA / max(NumB, 1)
        dist_to_coast_m   = pulled by FID from the Ike-2008 training-time
                            CSV, since the coastline is a geographic invariant
    - dropping the centroid_x/y and TBFA columns (they are not in v2's input set)
    - re-ordering features to match the training manifest
    - scaling with the saved StandardScaler
    - running inference on the v2 best checkpoint
    - summing predictions across all valid cells

The ground-truth total is read from the same shapefile that supplies the
training target (`outputs/debris_volume/Grid_250_with_debris_volume.shp`).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import geopandas as gpd

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR))
from model import PhysicsInformedDebrisNN, split_inputs

# ----- paths (defaults; overridable via CLI) -----
PROJECT_ROOT = THIS_DIR.parent
INPUT_PARAMS_DIR = PROJECT_ROOT / "outputs" / "final_input_for_debris_volume_model"
GT_SHP = PROJECT_ROOT / "outputs" / "debris_volume" / "Grid_250_with_debris_volume.shp"
DEFAULT_RUN_DIR = THIS_DIR / "outputs" / "run_v2"
ENGINEERED_CSV = THIS_DIR / "engineered_input_2026_05_04.csv"
DEFAULT_MANIFEST_PATH = THIS_DIR / "feature_groups_2026_05_04.json"

# Scenarios -- (storm_id, file_year, display_year)
SCENARIOS = [
    ("ike",    2019, 2020),
    ("ike",    2030, 2030),
    ("ike",    2040, 2040),
    ("fema33", 2019, 2020),
    ("fema33", 2030, 2030),
    ("fema33", 2040, 2040),
    ("fema36", 2019, 2020),
    ("fema36", 2030, 2030),
    ("fema36", 2040, 2040),
]
STORM_LABELS = {"ike": "Hurricane Ike", "fema33": "FEMA33", "fema36": "FEMA36"}

# Numbers reported in Table 1 of the manuscript (case_study.tex, original NN)
PAPER_TOTALS = {
    ("ike",    2020): 1_695_090,
    ("ike",    2030): 1_802_706,
    ("ike",    2040): 1_901_761,
    ("fema33", 2020):   968_645,
    ("fema33", 2030): 1_126_164,
    ("fema33", 2040): 1_325_042,
    ("fema36", 2020): 2_786_767,
    ("fema36", 2030): 3_096_080,
    ("fema36", 2040): 3_394_111,
}

# NB: out_dir is computed inside main() based on --run-dir argument.


def load_manifest(manifest_path: Path):
    with open(manifest_path) as f:
        m = json.load(f)
    feature_order = m["monotone_inc"] + m["monotone_dec"] + m["free"]
    return feature_order, len(m["monotone_inc"]), len(m["monotone_dec"])


def load_model(run_dir: Path, n_inc: int, n_dec: int, n_free: int, device: str):
    """Load model with the architecture saved in the run's manifest.json."""
    saved_args = {}
    manifest_run = run_dir / "manifest.json"
    if manifest_run.is_file():
        with open(manifest_run) as f:
            saved_args = json.load(f).get("args", {})
    h_inc = tuple(saved_args.get("h_inc", [32, 16]))
    h_dec = tuple(saved_args.get("h_dec", [16, 8]))
    h_free = tuple(saved_args.get("h_free", [32, 16]))
    dropout = saved_args.get("dropout", 0.1)
    model = PhysicsInformedDebrisNN(
        n_inc=n_inc, n_dec=n_dec, n_free=n_free,
        h_inc=h_inc, h_dec=h_dec, h_free=h_free, dropout=dropout,
    ).to(device)
    ckpt = torch.load(run_dir / "model_best.pth", map_location=device, weights_only=False)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()
    return model, ckpt


def get_dist_to_coast_mapping():
    """Return dict {FID: dist_to_coast_m} from the Ike-2008 engineered CSV.

    `dist_to_coast_m` is computed from cell geometry + OW threshold and is
    *geographic-invariant*; we re-use the exact same mapping for every
    scenario so the v2 model sees a consistent spatial feature regardless
    of what year is being predicted.
    """
    df = pd.read_csv(ENGINEERED_CSV)[["FID", "dist_to_coast_m"]]
    df["FID"] = df["FID"].astype(int)
    return dict(zip(df["FID"].values, df["dist_to_coast_m"].values))


def engineer_scenario(df_raw: pd.DataFrame, dist_map: dict) -> pd.DataFrame:
    """Engineer features for one scenario's input CSV.

    Replicates the same transformations used by `prepare_features.py`:
      - mean_bldg_size_m2 = TBFA / max(NumB, 1)
      - dist_to_coast_m   = looked up from the geographic-invariant mapping
      - centroid_x / centroid_y / TBFA are dropped (not in v2's input set).
    """
    df = df_raw.copy()
    df["FID"] = df["FID"].astype(int)
    nb = df["NumB"].astype(float).values
    tbfa = df["TBFA"].astype(float).values
    df["mean_bldg_size_m2"] = np.where(nb > 0, tbfa / np.maximum(nb, 1.0), 0.0)
    df["dist_to_coast_m"] = df["FID"].map(dist_map).astype(float)
    # v7d: hazard x building interaction features (compute on the fly if columns
    # are referenced by the manifest but absent from the per-scenario CSV)
    for haz in ("SD", "WH", "MF"):
        col = f"{haz}_NumB"
        if col not in df.columns and haz in df.columns:
            df[col] = df[haz].astype(float).values * nb
    return df


@torch.no_grad()
def predict_scenario(model, scaler, feature_order, n_inc, n_dec, df_eng,
                     device: str, batch_size: int = 4096):
    feats_present = [c for c in feature_order if c in df_eng.columns]
    missing = [c for c in feature_order if c not in df_eng.columns]
    if missing:
        raise ValueError(f"Missing features: {missing}")

    # rows that are fully populated
    valid_mask = ~df_eng[feature_order].isna().any(axis=1)
    n_valid = int(valid_mask.sum())
    n_total = len(df_eng)
    valid = df_eng.loc[valid_mask].copy()

    X = valid[feature_order].to_numpy(dtype=np.float32)
    X_scaled = scaler.transform(X).astype(np.float32)

    preds = np.zeros(len(valid), dtype=np.float32)
    for i in range(0, len(X_scaled), batch_size):
        xb = torch.tensor(X_scaled[i:i+batch_size], dtype=torch.float32, device=device)
        x_inc, x_dec, x_free = split_inputs(xb, n_inc, n_dec)
        preds[i:i+batch_size] = model(x_inc, x_dec, x_free).cpu().numpy()

    valid["pred_m3"] = preds
    full = df_eng[["FID"]].merge(valid[["FID", "pred_m3"]], on="FID", how="left")
    full["pred_m3"] = full["pred_m3"].fillna(0.0)
    return full, n_valid, n_total


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--run-dir", type=str, default=str(DEFAULT_RUN_DIR),
                   help="model run directory (with model_best.pth, scaler.pkl)")
    p.add_argument("--manifest", type=str, default=str(DEFAULT_MANIFEST_PATH),
                   help="feature-groups JSON manifest")
    p.add_argument("--label", type=str, default="v2",
                   help="label used in plots / filenames")
    p.add_argument("--calibrate", action="store_true",
                   help="apply a single multiplicative calibration "
                        "constant c = mean(y_train) / mean(pred_train) so the "
                        "model's mean prediction matches the training mean. "
                        "Preserves monotonicity and non-negativity by construction.")
    return p.parse_args()


def main():
    args = parse_args()
    run_dir = Path(args.run_dir)
    manifest_path = Path(args.manifest)
    label = args.label

    out_dir = run_dir / "scenario_comparison"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading manifest ({manifest_path}), scaler, model from {run_dir} ...")
    feature_order, n_inc, n_dec = load_manifest(manifest_path)
    n_free = len(feature_order) - n_inc - n_dec
    scaler = joblib.load(run_dir / "scaler.pkl")
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"  device = {device}")
    model, ckpt = load_model(run_dir, n_inc, n_dec, n_free, device)
    print(f"  {label} best epoch = {ckpt['epoch']}")
    dist_map = get_dist_to_coast_mapping()
    print(f"  dist-to-coast lookup loaded ({len(dist_map)} FIDs)")

    # Read final_metrics.json to compute calibration constant if requested.
    cal_factor = 1.0
    if args.calibrate:
        with open(run_dir / "final_metrics.json") as f:
            fm = json.load(f)
        train_mean_true = float(fm["train"]["mean_true"])
        train_mean_pred = float(fm["train"]["mean_pred"])
        cal_factor = train_mean_true / train_mean_pred if train_mean_pred > 0 else 1.0
        print(f"  calibration: c = E[y_train] / E[pred_train] = "
              f"{train_mean_true:.2f} / {train_mean_pred:.2f} = {cal_factor:.3f}")

    # Ground truth (Ike 2008 only)
    print("\nLoading ground-truth Ike-2008 volumes ...")
    gdf_y = gpd.read_file(GT_SHP)
    gdf_y["FID"] = gdf_y["FID"].astype(int)
    gt_total = float(gdf_y["volume_m3"].dropna().sum())
    gt_n = int(gdf_y["volume_m3"].notna().sum())
    print(f"  GT cells (non-NaN volume): {gt_n}, total = {gt_total:,.0f} m^3")

    # In-sample sanity: prediction on the Ike-2008 training-time inputs
    print(f"\n[sanity] {label} prediction on Ike-2008 (training-time inputs) ...")
    df_2008 = pd.read_csv(INPUT_PARAMS_DIR / "ike" / "2008" / "final_input_parameters.csv")
    df_2008_eng = engineer_scenario(df_2008, dist_map)
    pred_2008, nv, nt = predict_scenario(model, scaler, feature_order, n_inc, n_dec,
                                          df_2008_eng, device)
    pred_2008["pred_m3"] = pred_2008["pred_m3"] * cal_factor
    pred_2008_total = float(pred_2008["pred_m3"].sum())
    print(f"  cells = {nv}/{nt}, total predicted = {pred_2008_total:,.0f} m^3 "
          f"(GT = {gt_total:,.0f} m^3, diff = {pred_2008_total-gt_total:+,.0f} "
          f"= {(pred_2008_total/gt_total-1)*100:+.1f}%)")

    # Forward scenarios
    rows = []
    rows.append({
        "scenario_label": "Ike (training-time, 2008)",
        "storm": "ike", "display_year": 2008, "is_training_data": True,
        "v2_total_m3": pred_2008_total,
        "gt_total_m3": gt_total,
        "paper_total_m3": np.nan,
    })

    print("\n[scoring all 9 forward scenarios] ...")
    for storm, file_year, disp_year in SCENARIOS:
        csv_path = INPUT_PARAMS_DIR / storm / str(file_year) / "final_input_parameters.csv"
        if not csv_path.is_file():
            print(f"  [skip] {csv_path} not found")
            continue
        df_raw = pd.read_csv(csv_path)
        df_eng = engineer_scenario(df_raw, dist_map)
        pred, nv, nt = predict_scenario(model, scaler, feature_order, n_inc, n_dec,
                                         df_eng, device)
        pred["pred_m3"] = pred["pred_m3"] * cal_factor
        v2_total = float(pred["pred_m3"].sum())
        paper_total = PAPER_TOTALS[(storm, disp_year)]
        delta_abs = v2_total - paper_total
        delta_pct = (v2_total / paper_total - 1) * 100
        print(f"  {storm:6s} {disp_year}: cells={nv}/{nt}, v2={v2_total:,.0f}, "
              f"paper={paper_total:,.0f}, delta={delta_abs:+,.0f} ({delta_pct:+.1f}%)")
        rows.append({
            "scenario_label": f"{STORM_LABELS[storm]} ({disp_year})",
            "storm": storm, "display_year": disp_year, "is_training_data": False,
            "v2_total_m3": v2_total,
            "gt_total_m3": gt_total if storm == "ike" and disp_year == 2020 else np.nan,
            "paper_total_m3": float(paper_total),
        })

    df = pd.DataFrame(rows)
    df["delta_vs_paper_m3"] = df["v2_total_m3"] - df["paper_total_m3"]
    df["delta_vs_paper_pct"] = (df["v2_total_m3"] / df["paper_total_m3"] - 1) * 100
    df.to_csv(out_dir / "scenario_totals.csv", index=False)

    # Pretty print
    print("\n========================== SUMMARY TABLE ==========================")
    pretty = df.copy()
    for c in ["v2_total_m3", "gt_total_m3", "paper_total_m3", "delta_vs_paper_m3"]:
        pretty[c] = pretty[c].apply(lambda x: f"{x:,.0f}" if pd.notna(x) else "—")
    pretty["delta_vs_paper_pct"] = pretty["delta_vs_paper_pct"].apply(
        lambda x: f"{x:+.1f}%" if pd.notna(x) else "—")
    print(pretty[["scenario_label", "gt_total_m3", "paper_total_m3", "v2_total_m3",
                  "delta_vs_paper_m3", "delta_vs_paper_pct"]].to_string(index=False))

    # ---- Plot --------------------------------------------------------
    forward = df[~df["is_training_data"]].copy()
    forward["storm_label"] = forward["storm"].map(STORM_LABELS)

    storms_in_order = ["ike", "fema33", "fema36"]
    years_in_order = [2020, 2030, 2040]
    storm_colors = {"ike": "#1f77b4", "fema33": "#2ca02c", "fema36": "#d62728"}

    fig, ax = plt.subplots(figsize=(8, 4))
    fig.patch.set_alpha(0.0); ax.set_facecolor("none")

    bar_width = 0.36
    x_centers = np.arange(len(years_in_order) * len(storms_in_order))
    x_storm_groups = []
    labels = []

    for i, storm in enumerate(storms_in_order):
        for j, yr in enumerate(years_in_order):
            x = i * (len(years_in_order) + 1) + j
            x_storm_groups.append(x)
            labels.append(f"{yr}")
            sub = forward[(forward.storm == storm) & (forward.display_year == yr)]
            if sub.empty:
                continue
            paper_t = sub["paper_total_m3"].iloc[0] / 1e6
            v2_t = sub["v2_total_m3"].iloc[0] / 1e6
            ax.bar(x - bar_width/2, paper_t, bar_width,
                   color=storm_colors[storm], alpha=0.45, edgecolor="black",
                   linewidth=0.4, label="Original NN" if (i == 0 and j == 0) else None)
            ax.bar(x + bar_width/2, v2_t, bar_width,
                   color=storm_colors[storm], alpha=1.0, edgecolor="black",
                   linewidth=0.4, label=f"Physics {label}" if (i == 0 and j == 0) else None)

    # Ground truth horizontal line (Ike 2008 reference)
    ax.axhline(gt_total / 1e6, color="black", linestyle="--", linewidth=0.8,
               alpha=0.6,
               label=f"Ike 2008 ground truth ({gt_total/1e6:.2f} M m³)")

    ax.set_xticks(x_storm_groups)
    ax.set_xticklabels(labels, fontsize=8)
    ax.set_ylabel(r"Total predicted debris (×10$^{6}$ m$^3$)")
    # Storm group labels
    group_centers = []
    for i, storm in enumerate(storms_in_order):
        center = i * (len(years_in_order) + 1) + 1
        group_centers.append(center)
        ax.text(center, ax.get_ylim()[1] * 0.95, STORM_LABELS[storm],
                ha="center", va="top", fontsize=10, fontweight="bold",
                color=storm_colors[storm])
    ax.legend(loc="upper left", framealpha=0.0, fontsize=8)
    ax.grid(axis="y", linestyle=":", alpha=0.35)
    fig.tight_layout()
    fig.savefig(out_dir / "scenario_totals_bar.png", dpi=600,
                bbox_inches="tight", transparent=True, facecolor="none")
    plt.close(fig)

    # Companion plot: v2 / paper ratio (shows model agreement per scenario)
    fig, ax = plt.subplots(figsize=(7, 3))
    fig.patch.set_alpha(0.0); ax.set_facecolor("none")
    for i, storm in enumerate(storms_in_order):
        for j, yr in enumerate(years_in_order):
            x = i * (len(years_in_order) + 1) + j
            sub = forward[(forward.storm == storm) & (forward.display_year == yr)]
            if sub.empty:
                continue
            ratio = sub["v2_total_m3"].iloc[0] / sub["paper_total_m3"].iloc[0]
            ax.bar(x, ratio, 0.7, color=storm_colors[storm], alpha=0.85,
                   edgecolor="black", linewidth=0.4)
    ax.axhline(1.0, color="black", linewidth=0.6, linestyle="--", alpha=0.6)
    ax.set_xticks(x_storm_groups); ax.set_xticklabels(labels, fontsize=8)
    ax.set_ylabel(f"{label} total / Original NN total")
    for i, storm in enumerate(storms_in_order):
        center = i * (len(years_in_order) + 1) + 1
        ax.text(center, ax.get_ylim()[1] * 0.95, STORM_LABELS[storm],
                ha="center", va="top", fontsize=10, fontweight="bold",
                color=storm_colors[storm])
    ax.grid(axis="y", linestyle=":", alpha=0.35)
    fig.tight_layout()
    fig.savefig(out_dir / "scenario_totals_ratio.png", dpi=600,
                bbox_inches="tight", transparent=True, facecolor="none")
    plt.close(fig)

    print(f"\nOutputs:\n  {out_dir / 'scenario_totals.csv'}\n"
          f"  {out_dir / 'scenario_totals_bar.png'}\n"
          f"  {out_dir / 'scenario_totals_ratio.png'}")


if __name__ == "__main__":
    main()
