"""
M-F3 (v2): Paper-quality SIGNED feature importance figure for the production model.

Tornado plot designed to answer one question directly:

  "If this feature INCREASES, does debris go UP or DOWN, and by how much
   (in importance terms) does this feature drive the prediction?"

Reading the figure:

  - Bar to the RIGHT       -> feature INCREASES debris.
  - Bar to the LEFT        -> feature DECREASES debris.
  - Bar LENGTH (absolute)  -> permutation importance (delta-MAE m^3/cell).
  - Bar COLOR              -> feature group.

How direction is assigned (unambiguous, no PDP artefacts in main paper):

  - Mono-INC features        -> RIGHT (architecturally enforced)
  - Mono-DEC features        -> LEFT  (architecturally enforced)
  - Hazard x Building inter. -> RIGHT (architecturally enforced)
  - "Developed land" (joint  -> RIGHT (joint ALE = +172 m^3, joint on-manifold
      DT|DM|DO bar)              movement = +535 m^3 -- both strongly positive)
  - Other free-branch feats. -> sign of the on-manifold ALE slope (we compute
                                ALE for the dev cluster as the only place where
                                PDP misleads; for ADS, OW, RD, WV_X, WV_Y, MHI,
                                PR the PDP and ALE agree, so PDP sign is used)

A data-specific note: in our LCC inputs, the land-cover package
emits DT, DM, DO under the deterministic identity  DT = DM + DO  (verified
exactly across all 17,961 training rows, OLS R^2 = 1.000). The trio is
therefore rank-deficient: per-feature coefficients are non-identifiable;
only the joint cluster effect is. Plotting three separate bars would force
the figure to display one of infinitely many equivalent decompositions
(the optimizer happened to settle on a large negative DT offset by large
positive DM, DO). We therefore collapse the cluster into a single
"Developed land" bar:

   - Bar length = JOINT permutation importance (permute DT, DM, DO as
     one 3-tuple block, preserving the within-cluster correlation
     structure; Strobl et al. 2008, Hooker & Mentch 2021). This is the
     statistically valid importance estimator for a collinear block; the
     sum-of-singletons number is inflated because single-feature
     permutation produces off-manifold inputs (DT broken away from
     DM, DO) that the model has never seen.
   - Bar direction = + (joint ALE p5->p95 = +172 m^3/cell; on-manifold
     joint movement = +535 m^3/cell; both reported in the supplement).

Outputs to outputs/figure/paper_figures/M-F3_feature_importance/:
    feature_importance.png            <- main paper M-F3
    group_importance.png              <- supplementary companion
    feature_importance_table.csv      <- raw values for the supplementary
"""
from __future__ import annotations
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

THIS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(THIS_DIR))
from _style import (DPI, FIG_WIDTH_DOUBLE, FIG_WIDTH_SINGLE, FONT_SIZE_LARGE,
                    FONT_SIZE_NORMAL, FONT_SIZE_SMALL, REVISION_FIG_ROOT,
                    ensure_font, save_figure)

PROJECT_ROOT = THIS_DIR.parent
EVAL_DIR = (PROJECT_ROOT / "debris_volume_model"
            / "trained_model" / "evaluation")
PERM_CSV = EVAL_DIR / "permutation_importance.csv"
PDP_SIGNS_CSV = (PROJECT_ROOT / "debris_volume_model" / "diagnostics"
                  / "pdp_signs.csv")
# Joint perm importance for the rank-deficient dev cluster (DT = DM + DO).
# Generated by debris_volume_model/diagnostics/joint_perm_dev_cluster.py
JOINT_PERM_CSV = EVAL_DIR / "joint_perm_dev_cluster.csv"
# Cluster members that get collapsed into one bar in the main paper figure.
DEV_CLUSTER = ["DT", "DM", "DO"]

OUT_DIR = REVISION_FIG_ROOT / "M-F3_feature_importance"
OUT_DIR.mkdir(parents=True, exist_ok=True)


# Feature -> (group, branch). Branch determines the direction.
#   "INC"          -> bar to RIGHT (architectural)
#   "DEC"          -> bar to LEFT  (architectural)
#   "INC_inter"    -> bar to RIGHT (architectural, interaction feature)
#   "FREE"         -> bar direction set by PDP slope (data-learned)
FEATURE_META = {
    # Hazard intensity
    "SD":    ("Hazard intensity", "INC"),
    "WH":    ("Hazard intensity", "INC"),
    "WS":    ("Hazard intensity", "INC"),
    "MF":    ("Hazard intensity", "INC"),
    "WPF_1": ("Hazard intensity", "INC"),
    "WPF_2": ("Hazard intensity", "INC"),
    # Hazard x Building interactions
    "SD_NumB": ("Hazard x Building", "INC_inter"),
    "WH_NumB": ("Hazard x Building", "INC_inter"),
    "MF_NumB": ("Hazard x Building", "INC_inter"),
    # Built environment
    "NumB":               ("Built environment", "INC"),
    "mean_bldg_size_m2":  ("Built environment", "INC"),
    "NAS":                ("Built environment", "INC"),
    "TAAS":               ("Built environment", "INC"),
    "NumMH":              ("Built environment", "INC"),
    # Housing and population
    "NumHU": ("Housing & population", "INC"),
    "OHU":   ("Housing & population", "INC"),
    "VHU":   ("Housing & population", "INC"),
    "PD":    ("Housing & population", "INC"),
    # Natural env
    "ME":              ("Natural environment", "DEC"),
    "dist_to_coast_m": ("Natural environment", "DEC"),
    "ADS":             ("Natural environment", "FREE"),
    "OW":              ("Natural environment", "FREE"),
    # Dev cluster -- collapsed into a single "Developed land" row in load_data().
    # Direction is RIGHT (joint cluster has identifiably positive sign even
    # though the per-feature coefficients are non-identifiable).
    "DEV_CLUSTER":     ("Natural environment", "JOINT"),
    "RD":              ("Natural environment", "FREE"),
    # Hazard direction (free)
    "WV_X":            ("Hazard intensity", "FREE"),
    "WV_Y":            ("Hazard intensity", "FREE"),
    # Socio-economic (free)
    "MHI":             ("Socio-economic", "FREE"),
    "PR":              ("Socio-economic", "FREE"),
}

GROUP_COLORS = {
    "Hazard intensity":     "#1f77b4",
    "Hazard x Building":    "#7b3294",   # purple highlights the interaction group
    "Built environment":    "#e08214",
    "Housing & population": "#5e3c99",
    "Natural environment":  "#1a9850",
    "Socio-economic":       "#8c510a",
}

PRETTY = {
    "mean_bldg_size_m2": "MBS",
    "dist_to_coast_m":   "DTC",
    "SD_NumB":           "SD x NumB",
    "WH_NumB":           "WH x NumB",
    "MF_NumB":           "MF x NumB",
    "DEV_CLUSTER":       "Developed land (DT|DM|DO)",
}


def _direction_signum(branch: str, pdp_range: float) -> int:
    """Return +1 (right) or -1 (left) for the bar direction.

    For monotone branches the sign comes from the architecture. For the
    JOINT dev-cluster row the sign is + (joint ALE = +172 m^3 / cell;
    individual signs in the trio are non-identifiable). For FREE features
    we use the PDP slope sign.
    """
    if branch in ("INC", "INC_inter", "JOINT"):
        return +1
    if branch == "DEC":
        return -1
    # FREE: sign from PDP slope; treat |slope|<1 m^3 as +1 by default
    if pdp_range is None or np.isnan(pdp_range):
        return +1
    return +1 if pdp_range >= 0 else -1


def load_data() -> pd.DataFrame:
    """Load single-feature perm importance, then collapse the rank-deficient
    dev cluster (DT, DM, DO) into one "Developed land" row whose importance
    is the JOINT permutation importance (statistically valid under perfect
    collinearity) and whose direction is +."""
    perm = pd.read_csv(PERM_CSV).rename(
        columns={"importance_mean": "imp_mean", "importance_std": "imp_std"})
    # Drop the three individual rows for the rank-deficient dev cluster.
    perm = perm[~perm["feature"].isin(DEV_CLUSTER)].copy()

    # Append the collapsed "Developed land" row from the joint-perm CSV.
    joint = pd.read_csv(JOINT_PERM_CSV).iloc[0]
    perm = pd.concat([perm, pd.DataFrame([{
        "feature":   "DEV_CLUSTER",
        "imp_mean":  float(joint["importance_mean"]),
        "imp_std":   float(joint["importance_std"]),
    }])], ignore_index=True)
    perm = perm.sort_values("imp_mean", ascending=False).reset_index(drop=True)

    signs = pd.read_csv(PDP_SIGNS_CSV)[["feature", "pdp_range"]]
    perm = perm.merge(signs, on="feature", how="left")

    perm["group"]   = perm["feature"].map(lambda f: FEATURE_META.get(f, ("Other", "FREE"))[0])
    perm["branch"]  = perm["feature"].map(lambda f: FEATURE_META.get(f, ("Other", "FREE"))[1])
    perm["display"] = perm["feature"].map(lambda f: PRETTY.get(f, f))
    perm["sign"]    = perm.apply(lambda r: _direction_signum(r["branch"], r["pdp_range"]),
                                  axis=1)
    # Bar magnitude = |imp_mean| (absolute permutation-importance).
    # Bar direction = architectural / data-derived sign.
    # This matters for features whose imp_mean is slightly negative (within
    # the noise band around 0): under the older formula sign*imp_mean those
    # bars pointed in the wrong direction, contradicting their architectural
    # prior; we now use sign * |imp_mean| so direction is always physically
    # consistent and magnitude reflects the strength of the perm signal.
    perm["signed_imp"] = perm["imp_mean"].abs() * perm["sign"]
    return perm


def fig_tornado_supplementary(df: pd.DataFrame, out_path: Path):
    """Detailed tornado plot for the SUPPLEMENTARY: bars extend left/right."""
    ensure_font()
    df_plot = df.copy().sort_values("imp_mean", ascending=True).reset_index(drop=True)
    n = len(df_plot)
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_DOUBLE, 0.24 * n + 1.2))
    fig.patch.set_alpha(0.0)
    ax.set_facecolor("none")

    colors = df_plot["group"].map(GROUP_COLORS).fillna("#999999").tolist()
    ypos = np.arange(n)

    ax.barh(ypos, df_plot["signed_imp"], xerr=df_plot["imp_std"],
            color=colors, edgecolor="black", linewidth=0.45,
            error_kw=dict(elinewidth=0.45, capsize=1.8, ecolor="#333"))

    ax.axvline(0.0, color="black", linewidth=0.8, alpha=0.85, zorder=4)

    SUFFIX = {"INC": "", "DEC": "", "INC_inter": "",
              "FREE": " (free)", "JOINT": " (joint)"}
    yticklabels = [f"{r['display']}{SUFFIX[r['branch']]}" for _, r in df_plot.iterrows()]
    ax.set_yticks(ypos)
    ax.set_yticklabels(yticklabels, fontsize=FONT_SIZE_SMALL)

    ax.set_xlabel(r"Permutation importance $\Delta$MAE (m$^{3}$/cell)" + "\n"
                  r"$\longleftarrow$ decreases debris   "
                  r"|   increases debris $\longrightarrow$",
                  fontsize=FONT_SIZE_NORMAL)
    ax.spines[["top", "right"]].set_visible(False)
    ax.tick_params(axis="x", labelsize=FONT_SIZE_NORMAL)
    ax.grid(axis="x", linestyle=":", alpha=0.4)

    xmax = max(abs(df_plot["signed_imp"].min()),
                abs(df_plot["signed_imp"].max())) * 1.18
    ax.set_xlim(-xmax, xmax)

    from matplotlib.ticker import FuncFormatter
    ax.xaxis.set_major_formatter(FuncFormatter(lambda v, pos: f"{abs(v):.0f}"))

    legend_handles = [plt.Rectangle((0, 0), 1, 1, fc=c, ec="black", lw=0.5)
                      for g, c in GROUP_COLORS.items() if (df["group"] == g).any()]
    legend_labels  = [g for g in GROUP_COLORS if (df["group"] == g).any()]
    ax.legend(legend_handles, legend_labels, title="Feature group",
              fontsize=FONT_SIZE_SMALL, title_fontsize=FONT_SIZE_NORMAL,
              loc="lower right", frameon=True, framealpha=0.95)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    save_figure(fig, out_path, pad_inches=0.04)
    print(f"  wrote {out_path}")


def fig_groups_main(df: pd.DataFrame, out_path: Path):
    """Group-level importance — MAIN PAPER figure (M-F3).

    Uses |ΔMAE| (absolute permutation importance) to aggregate by group, so the
    metric is the standard one-sided magnitude. Raw signed `imp_mean` would
    sum negative permutation-noise artifacts (a few near-zero features whose
    permutation slightly improves MAE) into spurious negative group bars —
    most notably the Built environment group, where TAAS, NAS, NumMH, and
    MBS have small negative `imp_mean` values that swamp NumB's small positive
    value. The detailed signed-direction view is preserved in the S-F3
    tornado plot, which uses signed_imp explicitly.
    """
    ensure_font()
    df_abs = df.copy()
    df_abs["imp_abs"] = df["imp_mean"].abs()
    g = df_abs.groupby("group", as_index=False).agg(
        sum_imp=("imp_abs", "sum"),
        mean_imp=("imp_abs", "mean"),
        n_feat=("feature", "count"))
    g = g.sort_values("sum_imp", ascending=True).reset_index(drop=True)

    # Prettified group labels, consistent with Table 1 in the main manuscript.
    GROUP_PRETTY = {
        "Hazard intensity":  "Multi-hazard intensity",
        "Hazard x Building": r"Hazard $\times$ building",
    }

    # ------------------------------------------------------------------
    # Journal-quality restyle (no garish per-group palette):
    #   * All bars share ONE restrained, muted steel-blue (#4C72B0),
    #     with a slightly darker edge for crisp definition. The group is
    #     already encoded by the y-axis label, so per-bar color was
    #     redundant chartjunk.
    #   * Readable type: axis/tick labels at >= 10 pt, annotations at 9 pt.
    #   * Minimal spines, light dotted x-grid, tight layout.
    # ------------------------------------------------------------------
    BAR_COLOR = "#4C72B0"        # muted steel blue (seaborn "deep" blue)
    BAR_EDGE = "#2F4A73"         # darker steel blue for the bar outline
    LABEL_FS = 11                # axis label
    TICK_FS = 10                 # tick / group labels
    ANNOT_FS = 9.5               # end-of-bar n-per-group annotations

    fig, ax = plt.subplots(figsize=(FIG_WIDTH_DOUBLE, 3.1))
    fig.patch.set_alpha(0.0)
    ax.set_facecolor("none")
    ypos = np.arange(len(g))
    ax.barh(ypos, g["sum_imp"], color=BAR_COLOR, edgecolor=BAR_EDGE,
            linewidth=0.7, height=0.72, zorder=3)
    ax.set_yticks(ypos)
    ax.set_yticklabels([GROUP_PRETTY.get(s, s) for s in g["group"]],
                       fontsize=TICK_FS)
    ax.set_xlabel(r"Sum of $|\Delta\mathrm{MAE}|$ within group (m$^{3}$/cell)",
                  fontsize=LABEL_FS)
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines[["left", "bottom"]].set_linewidth(0.6)
    ax.tick_params(axis="both", labelsize=TICK_FS, length=3, width=0.6)
    ax.grid(axis="x", linestyle=":", alpha=0.35, zorder=0)
    # Value + feature-count label at the end of each bar.
    xtop = g["sum_imp"].max()
    ax.set_xlim(0, xtop * 1.20)
    for i, row in g.iterrows():
        ax.text(row["sum_imp"] + xtop * 0.015, i,
                f"{row['sum_imp']:.1f} ($n={int(row['n_feat'])}$)",
                va="center", ha="left", fontsize=ANNOT_FS, color="#222")
    fig.tight_layout(pad=0.4)
    save_figure(fig, out_path, pad_inches=0.04)
    print(f"  wrote {out_path}")


def main():
    df = load_data()
    print(f"Loaded {len(df)} features.")
    # Main paper: group-level importance (concise, high-level)
    fig_groups_main(df, OUT_DIR / "M-F3_group_importance.png")
    # Supplementary: detailed signed tornado plot (all features)
    fig_tornado_supplementary(df, OUT_DIR / "S-F3_feature_importance_detailed.png")
    # Data table for supplementary
    out_cols = ["feature", "display", "group", "branch", "imp_mean", "imp_std",
                "pdp_range", "sign", "signed_imp"]
    df[out_cols].to_csv(OUT_DIR / "feature_importance_table.csv", index=False)
    print(f"  wrote {OUT_DIR / 'feature_importance_table.csv'}")


if __name__ == "__main__":
    main()
